# ---------- Build Stage ----------
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build:staging

# ---------- Production Stage ----------
FROM node:18-slim

WORKDIR /app

# Copy only what's needed for runtime
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package*.json ./

RUN npm install --omit=dev

ENV NODE_ENV=production

EXPOSE 4200

CMD ["node", "dist/tcg-trader/server/server.mjs"]
