version: '3.8'

services:

  backend:
    build:
      context: ./backend  # Path to your Django project
    container_name: tcg-trader-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env 
    networks:
      - app-network
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend  # Path to your Angular project
    container_name: tcg-trader-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    command: npm start

  gateway:
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge