FROM python:3.11-slim

WORKDIR /app

RUN apt update && apt install -y postgresql-client && apt clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN python -m pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt && pip install gunicorn

COPY . /app/

EXPOSE 8000

# Use Gunicorn to serve Django
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "api.wsgi:application"]
