# Generated by Django 5.1.7 on 2025-04-17 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0002_remove_pokemoncarddetails_weakness_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCardCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity_owned", models.PositiveIntegerField(default=0)),
                ("quantity_for_trade", models.PositiveIntegerField(default=0)),
                ("desired_quantity", models.PositiveIntegerField(default=0)),
                (
                    "card",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cards.card"),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.language",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "card", "language")},
            },
        ),
    ]
