# Generated by Django 5.1.7 on 2025-04-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_collections", "0001_initial"),
        ("cards", "0002_remove_pokemoncarddetails_weakness_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercardcollection",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_card_collection",
                to="cards.card",
            ),
        ),
    ]
