name: Build, Push and Redeploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for changes in frontend
      id: frontend_changes
      run: |
        git diff --exit-code --quiet HEAD^ HEAD frontend || echo "frontend changed"

    - name: Build and Push frontend Docker image
      if: steps.frontend_changes.outputs.changed == 'true'
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        file: ./frontend/Dockerfile.prod
        push: true
        tags: |
          ghcr.io/acetoshi/tcg-trader/frontend:latest
          ghcr.io/acetoshi/tcg-trader/frontend:${{ github.sha }}

    - name: Check for changes in backend
      id: backend_changes
      run: |
        git diff --exit-code --quiet HEAD^ HEAD backend || echo "backend changed"

    - name: Build and Push backend Docker image
      if: steps.backend_changes.outputs.changed == 'true'
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        file: ./backend/Dockerfile.prod
        push: true
        tags: |
          ghcr.io/acetoshi/tcg-trader/backend:latest
          ghcr.io/acetoshi/tcg-trader/backend:${{ github.sha }}

  redeploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/tcg-trader
            git pull origin main
            make redeploy-prod
